[package]
name = "donut-live"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = "fat"
codegen-units = 1

[dependencies.httparse]
version = "1.8.0"
default-features = false

[dependencies.clap]
version = "4.3.11"
default-features = false
features = ["std", "derive", "help", "color", "usage", "error-context"]

[dependencies.uriparse]
version = "0.6.4"
default-features = false