[package]
name = "donut-live"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/splurf/donut.live"
authors = ["Evan Schwartzentruber <evandotschwartzentruber@gmail.com>"]


[dependencies.clap]
version = "4.5.6"
default-features = false
features = ["std", "derive", "help", "color", "usage", "error-context", "string"]

[dependencies.httparse]
version = "1.8.0"


[profile.release]
lto = true
codegen-units = 1
