[package]
name = "donut-live"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/splurf/donut.live"
authors = ["Evan Schwartzentruber <evandotschwartzentruber@gmail.com>"]

[dependencies.clap]
version = "4.5.1"
default-features = false
features = ["std", "derive", "help", "color", "usage", "error-context"]

[dependencies.httparse]
version = "1.8.0"

[dependencies.uriparse]
version = "0.6.4"

[profile.release]
lto = true
codegen-units = 1