[package]
name = "donut-live"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.httparse]
version = "1.8.0"
default-features = false

[dependencies.const_format]
version = "0.2.30"
default-features = false