[package]
name = "donut-live"
version = "0.1.0"
edition = "2021"


[dependencies]
clap = { version = "4.5.7", default-features = false, features = [
    "std",
    "derive",
    "help",
    "color",
    "usage",
    "error-context",
] }
httparse = "1.9.3"
artem = "3.0.0"
image = { version = "0.25.1", default-features = false, features = ["rayon", "gif"] }
rayon = "1.10.0"


[profile.release]
lto = true
codegen-units = 1
